---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: zookeeper-1
    image: centos:7
    command: /sbin/init
    privileged: True
    groups:
      - zookeeper-nodes
provisioner:
  name: ansible
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
  inventory:
    host_vars:
      zookeeper-1:
        zookeeper_id: 1
scenario:
  name: default
